@startuml
!theme vibrant

title 
<:sparkles:> Natalie's Proposed Pipeline for the <:sparkles:>
Creation of Novel Emulate3D Simulations of Walmart Sites
<$Swslg*0.05>
end title
:Assigned a new Walmart site to model;

:Take the latest site code and
strip out the parts that would
prevent it from being run in
an E3D test environment;
note right
    You should probably move this to
    being done after the mapping at the
    very least.
    ====
    Expand more on this later
    when you learn more about the PLC.
end note
    
    if (Has this site's type already been mapped in E3D) then (no)
    	partition "**Excel** and **Visio**\nCreating a 2D map and\nsurveying every position" {
			partition "**Visio**\nVisual Site Mapping"{
                :Attain documentation relevant documentation.
                If SPOC or Box is installed on site and a config exists
                try and use that in addition to any pictures you can get
                
                Additionally if SIS drawings and DWG Cad files exists
                try and find those because they contain useful
                information like length and connections;

                floating note left
                    A couple pieces of information
                    that would be really nice for you to
                    be able to display easily is grouped 
                    conveyors, lift objects, what direction
                    a conveyor/chain is going, and being able to
                    show what positions are complex and what are
                    relatively simple (I.E. simple conveyor or machine)
                end note
                floating note left
                    Create a Visio Bible as you're making
                    your first site map. Make sure to try to 
                    create standards that are simple
                    to conform to even for complex 
                    edge cases.
                end note

                :Begin making a top-down perspective map, 
                mapping position tiles from left to right,
                bottom to top, with each tile including
                the following:
                 - Position ID centered in plaintext
                 - Arrow indicating direction
                   - Horizontal Arrows belong on top
                   - Vertical Arrows belong on the left
                 - Bottom right **complexity indicator**

                When finished group each position tile
                and their associated markings together

                Note: Assume each conveyor is only
                1" wide in Visio, use the template
                positions for consistency
                
                Note: Do not take absolute size and
                position into account yet, only
                make something rough and simple;

                floating note left
                    Complexity Rankings for each position
                    in the bottom right of their respective squares:
                    Green is simple
                    - just a conveyor, double conveyor, etc
                    Yellow is a little complex
                    - lift and conveyor, has a sensor tree, etc
                    Red is very complex
                    - Requires a custom solution
                    - Think PSB dispensers and Shuttles
                    - Also called an SP or Special Position
                end note

                :Find and indicate the rough position
                and size of each interface panel, cabinet,
                and other devices that seem relevant.;

                floating note left
                 What kind of things do we want to map
                 and what kind of things do we want to ignore?
                end note

                :Begin assigning a light color to each
                group and take every position in each
                group and fill the whitespace with that
                group's color. 
                
                Repeated colors are encouraged for
                sites where two layouts are mirrored
                (Example: Group 10 and Group 40 in
                Walmart's 7015 site);

                floating note left
                 Do we want to create a dedicated
                 universal color pallete,
                 assign colors on a site-by-site basis,
                 or have specific color palletes
                 for specific customers?
                end note

                floating note left
                 Is there anything else we can add
                 to encourage legibility, information 
                 at a glance, and overall value?
                end note

                :Try and correct the dimensions of each position,
                noting their length and width where relevant using
                text. Do not visually change the length of your
                positions except if the difference is egregious.
                
                Try and put the length of a position as text in
                each dimension's particular Dimensional Arrows;
            }

			
			
			:Use Libreoffice Calc and open the file
			templates/E3D-DataGathering-Template.fods .
			Change "Template" in the filename to your site's name
			and save in the relevant directory.
			
			Begin filling it out by creating an entry for each
			position, then begin expanding each position's IO
			in the sheet. If you encounter a position that's complex
			just write down that it is IS complex and it can be come
			back to later.;
        	floating note left: Expand on this more later
            floating note left 
            	What kind of information
            	needs to be gathered?
           	end note

        }
        partition "**Emulate3D** and **Step7/TIA Portal**\nCreating and modifying\nSP catalogue items" {
            while (Does every <i>SP</i> in it already have a template?) is (no)
            floating note left
            	An SP is a __S__pecial __P__ositions
            	which consist of things like lifts,
            	barcode scanners on conveyors,
            	conformity checkers, etc.
            end note
            floating note left
            	I wonder if I should request
                IT to make a formal GIT server using
                something like gittea or just
                start using private GitHub repos
                because this is going to become
                *a lot* of data and *a lot*
                of pushes to somewhere
                we're all going to need to access
                easy peasy <:lemon:> squeezy
            end note
            
                :For each SP with no template:;
                	:Ask around with coworkers,
                     and see if they have any advice
                     for this particular machine.
                     
                     Try and find any opportunities
                     to use an already made template
                     and adapt it to this SP.;
                	:Isolate and run the function
                     block or code relevant to this
                     SP in it's own simple PLC program.
                     Use this as a test bench to create
                     a template for this SP to put
                     in the E3D Catalogue.;
                    :Finalize the template in E3D
                     for this SP. Save it and push
                     it to the shared repository
                     for E3D work with push notes.;
                	if (Was that the last SP?) then (yes)
                		break
                	else (no)
                	endif
            endwhile (yes)
            :Ensure validity of each SP
             that will be used in
             the project;
        } 
        :Confirm and correct placement
        and connections of every position;
        floating note left: Account for multi-position conveyors
        :Begin creating the model, starting
        with only conveyors and SPs;
        :Confirm NO/NC status of position
        photoeyes;
        :Begin placing position photoeyes
        in the model, confirming correct
        positioning if issues arise;
        :Fill out the tag table using
        already gathered inputs;
    else (yes)
    	:Ensure that this site conforms
        with it's previously created site type
        documentation and E3D Projects;
    endif
    
    while(Try and Connect to PLC) is (Doesn't work!) 
    	:Ensure DBs and Membits in
         the tag table are accurate,
         as well as the PLC's status
         and targeted IP;
    endwhile (Works!)
end
@enduml